[versions]
gearyPaper = "0.30.3"
blocky = "0.10.1"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
blocky = { module = "com.mineinabyss:blocky", version.ref = "blocky" }

minecraft-plugin-customblockdata = "com.jeff-media:custom-block-data:2.2.2"
minecraft-plugin-triumph-gui = "dev.triumphteam:triumph-gui:3.1.10"
